### ISSUE TITLE
Make median filter functions more forgiving when specifying kernel size

### ISSUE THREAD

**Issue by plaplant** [HERA-Team/hera_qm#101]
Right now, in functions like `medminfilt` in `xrfi.py`, a check is done to ensure that the specified kernel size is not larger than the size of the corresponding dimension. This is a useful check, but it would be more user-friendly to warn the user and carry on with the largest possible kernel size when a too-big kernel is specified. This would be especially helpful for RTP, since there are occasionally files that have very few time samples, and cause the XRFI step to break because the default kernel size is too large.

**Comment by adampbeardsley** [comment]
@jkerrigan could I convince you to handle this? I think it should be straightforward.

**Comment by jkerrigan** [comment]
Yea, I can handle this, but I think I'd go the opposite direction with the smallest reasonable kernel size. Just because medminfilt begins to bog down at the higher sizes.

**Comment by adampbeardsley** [comment]
I think the idea is that the user asked for a larger than possible kernel. So for example, if Kt=8, but the time dimension is only length 4. We should default to the length of the dimension (or maybe smaller if a buffer is required)

**Comment by jkerrigan** [comment]
Not sure how to approach this, but I don't think allowing the maximum kernel size will allow it to pass Travis. The medfiltering process takes an extended time to finish and apparently Travis times out after a long time?

**Comment by plaplant** [comment]
For testing purposes, could you perform a `select` operation to make the file shorter than it is on disk? 

Just to clarify: the current behavior when the user asks for a kernel dimension larger than the data size (as Adam said, if Ntimes=4, but the user specifies Kt=8) is that XRFI errors out. Instead, I'd prefer it to warn the user that the length along that dimension is smaller than the requested kernel size, and proceed with a kernel that is the largest size allowed (I believe it'd be 4 in the above example, but don't know for sure).

**Comment by plaplant** [comment]
Fixed by #190.
