### ISSUE TITLE
ant_metrics JSON representation is Python-specific

### ISSUE THREAD

**Issue by pkgw** [HERA-Team/hera_qm#112]
The ant_metrics JSON files currently used by the QM code currently represent most of their data structures as stringifications of Python data structures, e.g.:

```
{
  "xants": "[(50, 'x')]",
  "all_metrics": "[{'meanVijXPol': {(67, 'y'): 0.84893427048928449, ...
  ...
}
```

The whole point of using JSON as a file format is that it can represent such data structures natively, so that the files can be usefully interpreted by any piece of software that knows JSON (other programming languages, analysis packages like R, etc.). As it stands, one has to use our particular Python module to extract most of the information out of the file. A JSON-native representation of the existing data might look like:

```
{
  "xants": ["50x"],
  "all_metrics": [ {"meanVijXPol": { "67y": 0.84893427048928449, ...
  ...
}
```

using compactly-stringified antpol specifications to allow them to serve as dictionary keys.

Also, the `version_information` item should be expressed as a dictionary rather than the current string that consists of several items specified in English (`"hera_qm version: 1.0.  Git origin: https://github.com/..."`).

It almost surely doesn't make sense to do anything about this in the current season, but if there is ever a `hera_qm` 2.0, we should make these files more JSONic.

**Comment by adampbeardsley** [comment]
This shouldn't be an issue when we move to a standard format and support read/write in the metrics base class.
