### ISSUE TITLE
Make xrfi_run more modular

### ISSUE THREAD

**Issue by adampbeardsley** [HERA-Team/hera_qm#134]
xrfi_run started as a simple concept, but gradually grew to handle all kinds of different run modes. We should revamp it to be simpler but allow more flexible input. For example, passing in model and calfits files in addition to data files is kind of silly. We should just allow for one input, and tell it what's being passed in.

**Comment by jsdillon** [comment]
While you're doing this, can you add a test that exposes the error in #138 ? Thanks.

**Comment by plaplant** [comment]
Fixed by #190.
