### ISSUE TITLE
Kernel size exceeds data in some cases

### ISSUE THREAD

**Issue by jsdillon** [HERA-Team/hera_qm#140]
See `/lustre/aoc/projects/hera/H1C_IDR2/IDR2_1/2458114/zen.2458114.66640.xx.HH.uv.CAL_XRFI.xy.log`

The simplest solution here is to just flag the whole file. If the issue is that it's very few integrations, another possible solution is to concatenate with the previous/next file and then use them together to find RFI.

**Comment by adampbeardsley** [comment]
From the `hera_qm.xrfi` perspective, I think it makes most sense to flag the whole file. Concatenating with other files would have to be done on the analysis level, and maybe that's another avenue we can look at in parallel.

@jkerrigan Have we talked about this failure mode before? I vaguely remember this coming up, and we made a decision to have it error. But maybe I'm misremembering. What do you think about flagging all the data if your kernel size is bigger than the data?

**Comment by jsdillon** [comment]
Flagging the whole file is fine with me.
