### ISSUE TITLE
Move hera_cal.io.load_npz_flags to hera_qm

### ISSUE THREAD

**Issue by jsdillon** [HERA-Team/hera_qm#150]
Based on @AaronParsons's comments in https://github.com/HERA-Team/hera_cal/pull/293

This function is written to be dependent on choices made in xrfi.py. Perhaps we'd want to keep a thin wrapper in hera_cal.io.

Ideally, we'd move it here so that if we change xrfi, tests would break.

**Comment by adampbeardsley** [comment]
@jsdillon is this still relevant now that we've moved to UVFlag files?

**Comment by jsdillon** [comment]
I guess it would be nice to be able to read old files. Maybe we can unify this with a UVFlag reader in a way that spits out DataContainers. When I get to implementing this for hera_cal, I've give it some thought.

**Comment by jsdillon** [comment]
I think I just volunteered for this, didn't I?

**Comment by adampbeardsley** [comment]
Anything data container related is on you.

**Comment by mkolopanis** [comment]
Any updates on this?

**Comment by jsdillon** [comment]
Now that flags are defined in pyuvdata, I think we want to keep the load_flags as is in hera_cal. Let's close this.
