### ISSUE TITLE
running core functionality interactively is not easy / possible

### ISSUE THREAD

**Issue by nkern** [HERA-Team/hera_qm#155]
I'm trying to run some of the core functionality on data interactively in the stand-alone functions in `hera_qm.xrfi` (take for example `xrfi.cal_flag`), but I can't do that easily because the function requires an `argparse.ArgumentParser` as an argument, which can't really be created in an interactive environment (think a Jupyter notebook), short of having to create an object from scratch and manually fill in every single argument / kwarg by hand.

I know this is a design choice across the entire `hera_qm` repo, but I would suggest at some point we move to make all stand-alone, module-level functions (e.g. `xrfi.cal_flag`, or `xrfi.xrfi_run`) take arguments and kwargs directly, and have the argument parsing done at the script level (i.e. `xrfi_run.py`). This makes it easier (possible) to run these core functions interactively when we are trying to debug / answer research-level questions, but still allows us to use things like argument parsing at the script-level. Perhaps we can have a discussion about this sometime on an analysis telecon..

**Comment by adampbeardsley** [comment]
This is on my list for when we do the revamp. In the mean time, you can pass an empty list to the argument parser, or a list of the arguments you want to change from defaults. I know it’s not ideal, but should be a 1-2 line workaround for now. 
(I’m on mobile, but the exact syntax for this can be seen in the unit tests if I’m not quite right.)

**Comment by nkern** [comment]
Ah, I didn't even know you could do that! that actually solves most of my immediate problems! thanks!

**Comment by plaplant** [comment]
Fixed by #190.
