### ISSUE TITLE
2458108.51325 failed to finish for delay_xrfi

### ISSUE THREAD

**Issue by jsdillon** [HERA-Team/hera_qm#157]
In IDR2.1 we're just flagging the file. This could crop up again, so we should probably figure out why it failed.

**Comment by jkerrigan** [comment]
From what I can tell this observation is flagged 100% prior to delay_xrfi. When looking at the raw data there appears to be huge differences in the passband (e.g. compare between 0_122 and 1_122).

**Comment by jsdillon** [comment]
That's odd... if it were 100% flagged, it would skip delay_xrfi and skip. Any idea where it's getting stuck?

**Comment by adampbeardsley** [comment]
This issue seems to have been due to complex or overflagging prior to delay-xrfi. I'm going to replace this issue with a new one for a more general catch-all when delay_xrfi fails to converge.
