### ISSUE TITLE
Make ant metrics faster

### ISSUE THREAD

**Issue by adampbeardsley** [HERA-Team/hera_qm#162]

**Comment by adampbeardsley** [comment]
Probably can't compare all pairs of baselines next season. Need to find ways of reducing this.

**Comment by ianmalcolm** [comment]
Time profiling is listed in cprofile.log, in which cumtime stands for time consumption of a function and all functions in it. From the list I see that red_corr_metrics and mean_Vij_metrics are key functions that consume a lot of time.

Previously I thought get_data() returns small amount of data at a time. By using pdb, I found it can return multiple data at a time. For example, for JD2458105.12551. get_data(0,1,'xx') returns the time series for the following baseline:

(array([    1,  1379,  2757,  4135,  5513,  6891,  8269,  9647, 11025,
       12403, 13781, 15159, 16537, 17915, 19293, 20671, 22049, 23427,
       24805, 26183, 27561, 28939, 30317, 31695, 33073, 34451, 35829,
       37207, 38585, 39963, 41341, 42719, 44097, 45475, 46853, 48231,
       49609, 50987, 52365, 53743, 55121, 56499, 57877, 59255, 60633,
       62011, 63389, 64767, 66145, 67523, 68901, 70279, 71657, 73035,
       74413, 75791, 77169, 78547, 79925, 81303]),
 array([], dtype=int64))
 array([0])

Coarse memory profiling is shown in mprofile.png. From the figure I guess all the data are loaded into the memory. When calculating all metrics, all data are already in memory.

Then I did a fine memory profiling over read_miriad(), red_corr_metrics() and mean_Vij_metrics(), as shown in mprofile.log. It shows that read_miriad() loads data into memory. red_corr_metrics() and mean_Vij_metrics() do not really cause any extra memory occupation. Therefore if any performance improvement could be made, I think it could ordering the data fetching so that data locality inside of the CPU could be fully  used

[cprofile.log](https://github.com/HERA-Team/hera_qm/files/2211354/cprofile.log)
[mprofile.log](https://github.com/HERA-Team/hera_qm/files/2211355/mprofile.log)
![mprofile](https://user-images.githubusercontent.com/9103075/42964827-23b215e6-8b90-11e8-9d3e-633c161ef5ff.png)

**Comment by ianmalcolm** [comment]
For the very same i, j, and pol, as shown in the line listed [here](https://github.com/HERA-Team/hera_qm/blob/c9fcc45b9cf66ccf3cfe45bb24095fb3fe3c7476/hera_qm/ant_metrics.py#L92), the "get_data" function [here](https://github.com/HERA-Team/hera_qm/blob/c9fcc45b9cf66ccf3cfe45bb24095fb3fe3c7476/hera_qm/ant_metrics.py#L94) and the summation [here](https://github.com/HERA-Team/hera_qm/blob/c9fcc45b9cf66ccf3cfe45bb24095fb3fe3c7476/hera_qm/ant_metrics.py#L95) are called four times, which I guess are redundant. Am I correct If we change line 92-96 of ant_metrics.py to following snippet of code, we would have immediate performance improvement without any sacrifice?

```
        # list all involved antennas and polarisations
        ants = zip((i,j),pol)

        # continue the for-loop if involved ants/pols are all listed in xants
        if all([ant in xants for ant in ants]):
            continue

        # Fetch data once and calculate only once
        d = data.get_data(i, j, pol)
        s = np.nansum(np.abs(d))

        # write results back accordingly
        for ant, antpol in ants:
            if (ant, antpol) in xants:
                continue
            absVijMean[(ant, antpol)] += s
            visCounts[(ant, antpol)] += d.size
```

**Comment by ianmalcolm** [comment]
I tried the code above. It looks like:

  | ncalls | tottime | percall | cumtime | percall | filename:lineno(function)
-- | -- | -- | -- | -- | -- | --
Before: | 6 | 65.613 | 10.936 | 85.864 | 14.311 | ant_metrics.py:69(mean_Vij_metrics)
After: | 6 | 32.985 | 5.497 | 42.768 | 7.128 | ant_metrics.py:69(mean_Vij_metrics)

I also compared the output Json file before and after the change. They are the same.

**Comment by adampbeardsley** [comment]
That looks great @ianmalcolm! Am I reading this correctly that this will cut the time to calculate meanVij in half?

**Comment by ianmalcolm** [comment]
Here is another improvement:

Improve get_data in pyuvdata by replacing its [antpair2ind](https://github.com/RadioAstronomySoftwareGroup/pyuvdata/blob/3dedbcb4aa0ca5ebb0f9c62706f616f710ea3cd4/pyuvdata/uvdata.py#L2503) with the following version. Basically it is keeping a dictionary, as you suggested in our meeting, to accelerate antpair2ind.

```
    def antpair2ind(self, ant1, ant2):
        """
        Get blt indices for given (ordered) antenna pair.
        """

        #return np.where((self.ant_1_array == ant1) & (self.ant_2_array == ant2))[0]

        def __group_by_baseline(ant1arr,ant2arr):
            """
            Generate a dictionary to accelerate get_data. The key is antenna pair, or baselines
            in the form of (ant1, ant2). The value is the index (1st dimension of
            self.data_array) associated with that baseline.

            I would assume that while a dataset is opening by pyuvdata, its ant_1_arr,
            ant_2_arr, and data_array remain unchanged. Please refer to
            https://github.com/HERA-Team/hera_qm/issues/162 for the reason
            of having this dictionary.

            ant1arr -       self.ant_1_arr
            ant2arr -       self.ant_2_arr
            """
            __ant1 = ant1arr.reshape(-1,1)
            __ant2 = ant2arr.reshape(-1,1)
            __ind = np.arange(ant1arr.shape[0]).reshape(-1,1)

            # baseline index, not really blind :)
            blind = np.hstack((__ant1,__ant2,__ind))
            # baseline dictionary
            bldict = {}
            for (col0,col1,col2) in blind:
                if (col0,col1) in bldict:
                    bldict[(col0,col1)] = np.append(bldict[(col0,col1)],col2)
                else:
                    bldict[(col0,col1)] = [col2]

            return bldict

        try:
            self.bldict
        except AttributeError:
            self.bldict = __group_by_baseline(self.ant_1_array,self.ant_2_array)

        if (ant1,ant2) not in self.bldict:
            return []
        else:
            return self.bldict[(ant1,ant2)]
```
The self.bldict occupies 200KB memory for a full-size dataset, which is not a big deal.
The performance of mean_Vij_metrics, against the one that I commented two hours ago, looks like this:

ncalls | tottime | percall | cumtime | percall | filename:lineno(function)
-- | -- | -- | -- | -- | --
6 | 32.985 | 5.497 | 42.768 | 7.128 | ant_metrics.py:69(mean_Vij_metrics)
6 | 32.922 | 5.487 | 38.342 | 6.39 | ant_metrics.py:69(mean_Vij_metrics)

And the correctness of the changes to the code are ensured over the following datasets
zen.2458105.12551.xx.HH.uv
zen.2458105.12551.xy.HH.uv
zen.2458105.12551.yx.HH.uv
zen.2458105.12551.yy.HH.uv

**Comment by ianmalcolm** [comment]
@adampbeardsley Yes, you are reading this correctly.

**Comment by adampbeardsley** [comment]
This looks great. For the second improvement, there would be some more work to do if we want to get this incorporated into pyuvdata - for example, we can't assume the data array doesn't change (there are functions like `select`). But we could implement something like this directly in QM, where can can make that assumption.

**Comment by ianmalcolm** [comment]
Thanks to @jsdillon hera_cal.io.HERAData, the time consumption of ant_metrics_run.py is further cut down from 464.667 seconds to 383.035 seconds. Now the time performance looks like this

  | ncalls | tottime | percall | cumtime | percall | filename:lineno(function)
-- | -- | -- | -- | -- | -- | --
c9fcc45 (Originally) | 1 | 0.559 | 0.559 | 607.212 | 607.212 | ant_metrics_run.py
  | 6 | 65.613 | 10.936 | 85.864 | 14.311 | ant_metrics.py
  | 6 | 80.045 | 13.341 | 354.617 | 59.103 | ant_metrics.py
  | 383978 | 1.256 | 0 | 116.017 | 0 | get_data
6abf3dc | 1 | 0.459 | 0.459 | 464.677 | 464.677 | ant_metrics_run.py
  | 6 | 79.94 | 13.323 | 271.583 | 45.264 | red_corr_metrics
  | 6 | 33.121 | 5.52 | 38.379 | 6.396 | mean_Vij_metrics
  | 363068 | 0.945 | 0 | 20.172 | 0 | get_data
bb5192b (Now) | 1 | 0.479 | 0.479 | 383.057 | 383.057 | ant_metrics_run.py
  | 6 | 50.933 | 8.489 | 190.697 | 31.783 | red_corr_metrics
  | 6 | 28.884 | 4.814 | 31.241 | 5.207 | mean_Vij_metrics
  | 363068 | 1.034 | 0 | 3.12 | 0 | __getitem__

The limitation is that HERAData cannot handle fhd format, which is supported by UVData.

**Comment by mkolopanis** [comment]
do we want to call this closed now that we have HERAData as part of ant_metrics?

**Comment by adampbeardsley** [comment]
Yup, I think this is good to go. @ianmalcolm you can always come back to the issue if you want to update benchmarks.
