### ISSUE TITLE
RFI seems to be not completely flagged in 2458104

### ISSUE THREAD

**Issue by jsdillon** [HERA-Team/hera_qm#164]
Naomi noticed that the smooth_cal gains and flags on 2458104 show weird structure and inconsistent flagging. <img width="879" alt="screen shot 2018-06-26 at 11 36 21 am" src="https://user-images.githubusercontent.com/5281139/41932351-a5f4d024-7935-11e8-91d1-0be01034fcc9.png">

Most likely, there are times that should have been RFI flagged that didn't get flagged, though this needs to be dug into a bit. This might be due to the kind of issue we saw here: https://github.com/HERA-Team/HERA_Commissioning/issues/114 ... in fact, Zaki did mention that day 104 also saw similar issues to day 109.

**Comment by dannyjacobs** [comment]
FWIW that time is when Fornax is up.  Which one would notice more easily if the x axis were LST in hours not radians.

**Comment by adampbeardsley** [comment]
We're using this as a test case in our general explore RFI flagging strategies #193
