### ISSUE TITLE
Make xrfi python 3 compatible

### ISSUE THREAD

**Issue by adampbeardsley** [HERA-Team/hera_qm#165]

**Comment by adampbeardsley** [comment]
And the tests

**Comment by adampbeardsley** [comment]
Even though right now the delay filter is called at a script level, it will probably be brought into a xrfi_run() type function. At which point, xrfi will depend on aipy... maybe we need to rewrite a lot of aipy tools in uvtools and/or hera_cal?

**Comment by adampbeardsley** [comment]
As of right now xrfi is py3 compatible. But should we keep this open in light of the previous comment? What say @plaplant and @mkolopanis, keepers of code practices?

**Comment by mkolopanis** [comment]
from the aipy github main page:
> The 2.x release series of AIPY supports only Python 2. However, there is now a prototype version of AIPY 3.0

so even with that being brought in it might be py3 compatible

**Comment by adampbeardsley** [comment]
Good enough for me
