### ISSUE TITLE
Make ant metrics python 3 compatible

### ISSUE THREAD

**Issue by adampbeardsley** [HERA-Team/hera_qm#166]

**Comment by adampbeardsley** [comment]
and the tests

**Comment by adampbeardsley** [comment]
This is going to require getting rid of aipy call. @mkolopanis may do this during his revamp anyway.

**Comment by bhazelton** [comment]
when this issue is closed, please let me know so I can update M&C -- currently we're skipping the qm-related tests when in python 3

**Comment by mkolopanis** [comment]
almost impossible to fully test without all the dependencies being python-3 compatible but starting at version `v1.0-190-ga26f4b7`  on `ant_metrics_revamp` both ant_metrics and metrics_io should be python-3 compatible.

**Comment by mkolopanis** [comment]
there were some import problems, this version `v1.0-193-g464daa4` on ant_metrics revamp is the one where ant_metrics and metrics_io should be fully python 3 compatible.

**Comment by plaplant** [comment]
I think once we have the ant_metrics and xrfi revamps merged in, we'll make a branch where we turn on python3 building in travis, and iron out any lingering dependency issues then.

**Comment by mkolopanis** [comment]
this is being covered with #237
