### ISSUE TITLE
Make firstcal and omnical metrics python 3 compatible

### ISSUE THREAD

**Issue by adampbeardsley** [HERA-Team/hera_qm#167]

**Comment by adampbeardsley** [comment]
and the tests

**Comment by mkolopanis** [comment]
firstcal metrics is python 3 compatible right now, actually all of the repo _is_ what are our reservations on this?

**Comment by adampbeardsley** [comment]
I think we just forgot to close it. There aren't any more skip tests. Are we requiring py3 to pass before merge? I can't find anywhere in the .travis.yaml that says otherwise.

**Comment by mkolopanis** [comment]
we require travis passing, so by running both py2.7 and py3.6 on travis we require both passing in order to merge.

**Comment by adampbeardsley** [comment]
Yeah, that's what I thought. let's close this.
