### ISSUE TITLE
red_corr_cross_pol_metrics is hard coded to return z scores only

### ISSUE THREAD

**Issue by ShaneBechtel** [HERA-Team/hera_qm#173]
https://github.com/HERA-Team/hera_qm/blob/674ec636f1960a337d9004f7829076a4d5565ec1/hera_qm/ant_metrics.py#L364-L368

While examining the antenna metrics for all the HERA data, the supposed raw metrics for the redundancy correlation for the cross polarizations were shown be the same as the z scores for this metric. Upon examination of the antenna metrics code on line 368, it appears that the metric function is hard coded to only return the z scores for this metric, regardless of user input.

**Comment by jsdillon** [comment]
Oops... that was probably my fault. Good catch. Wanna make a PR? It should read `rawMetric=rawMetric`.

**Comment by mkolopanis** [comment]
Oh i may have been doing this too :P
