### ISSUE TITLE
pyuvdata polarization dictionary change breaks `hera_qm` tests

### ISSUE THREAD

**Issue by nkern** [HERA-Team/hera_qm#196]
Change in `pyuvdata` polarization standard is now breaking `hera_qm` `vis_metrics` and `xrfi` tests, although its a trivial change: just switching `XX` to `xx` etc. A `pyuvdata` PR introduces a standard way of parsing  polarization strings --> pyuvdata-standard strings, such that this won't be a problem in the future. My `noise_modeling` PR adds this fix into the two test files b/c its a trivial change..

**Comment by mkolopanis** [comment]
so this was closed by a PR right? and we can close it?
Remember we can also use: fixes #196 language in the top level comment of a PR to automatically close issues :smile:
