### ISSUE TITLE
harmonize docstrings

### ISSUE THREAD

**Issue by adampbeardsley** [HERA-Team/hera_qm#198]
We may actually want to bring this up to the wider HERA org, but at least within our own repo we should have some standard for docstring format. Personally I like the numpy format:
http://daouzli.com/blog/docstring.html#numpydoc

**Comment by mkolopanis** [comment]
I am also a fan of this style of docstring, or googledoc style http://daouzli.com/blog/docstring.html#googledoc

**Comment by adampbeardsley** [comment]
Ok, we voted on the telecon today and decided to adopt the google doc style

**Comment by adampbeardsley** [comment]
We revoted on the telecon today and changed back to numpy.
pydocstyle works with numpy.
