### ISSUE TITLE
sequential differencing code produces bad values when pad=True

### ISSUE THREAD

**Issue by plaplant** [HERA-Team/hera_qm#201]
The `sequential_diff` function in `vis_metrics.py` seems to produce invalid values when `pad=True`. The stated goal of the option is to keep the dimensions of the output the same as the input, but it seems to introduce poorly behaved values as output. The tests on travis show `invalid value encountered in sqrt`, indicating that a negative number was generated prior to the sqrt operation. The root cause of these warnings should be identified, because as it stands we cannot trust the results. If the cause cannot be identified, then the `pad=True` option should be removed.

**Comment by adampbeardsley** [comment]
bump @nkern

**Comment by plaplant** [comment]
Fixed by #225.
