### ISSUE TITLE
Make ant metrics uvh5 compatible

### ISSUE THREAD

**Issue by adampbeardsley** [HERA-Team/hera_qm#208]

**Comment by jsdillon** [comment]
If you're using `HERAData`, then you're probably most of the way there.

Are you also implementing partial io for ant metrics?

**Comment by adampbeardsley** [comment]
Agreed, this should be pretty easy. Just wanted to write it down so we don't forget.

partial io eventually - a bit lower on the priority list now that we're starting with six antennas.
