### ISSUE TITLE
Adhere to new filename convention

### ISSUE THREAD

**Issue by adampbeardsley** [HERA-Team/hera_qm#220]
Namely, we've agreed to stop keeping file extensions in the middle of filenames. For example, we currently make file like ...`uvh5.ant_metrics.hdf5`, which we would like to make ...`ant_metrics.hdf5`.

**Comment by adampbeardsley** [comment]
@jsdillon I'm trying to get a jump on this so I can keep testing the daily notebook with the new filenames. What are your thoughts on the lettering for adding steps to visibility files? For example, what should my RFI flagged uvh5 files look like?

**Comment by jsdillon** [comment]
We're not going to be making any new visibility files (except the final delay-filtered file and the LST-binned data).

**Comment by adampbeardsley** [comment]
Ok, well I need something for the xrfi_apply function (even if we're not using it in the pipeline). I'll just smack the R before the uvh5 and call it a day.

**Comment by adampbeardsley** [comment]
Ok, I think I've updated the filenames sufficiently for xrfi and ant_metrics. How much do we care about firstcal and omnical metrics, given that they don't currently connect to other boxes in the omnigraffle of doom?

**Comment by mkolopanis** [comment]
![](https://media.giphy.com/media/LwdtMSGiQ0Ako/giphy.gif)

**Comment by adampbeardsley** [comment]
wait, so did I already whole-ass the xrfi naming? or if I split it into two PRs would that be half-assing two things?
