### ISSUE TITLE
Address TODOs in test_xrfi

### ISSUE THREAD

**Issue by adampbeardsley** [HERA-Team/hera_qm#23]
I've removed these from the actual code, but we shouldn't lose track of them.

# TODO: noise tilts
# TODO: faint RFI
# TODO: combination of everything

**Comment by adampbeardsley** [comment]
Oh wow that formatting is pretty great.

**Comment by adampbeardsley** [comment]
After xrfi revamp

**Comment by adampbeardsley** [comment]
Some of this is going to be done along the way for @jkerrigan's ML paper. Care to comment a little Josh?

**Comment by jkerrigan** [comment]
Evaluations of the watershed XRFI alg in the ML paper will be based on actual HERA data with a pretty well known ground truth. So I can still add these performance tests, but they may or may not be as useful though.

**Comment by adampbeardsley** [comment]
I'm going to go ahead and close this... performance is a research question being pursued in a number of other places.
