### ISSUE TITLE
fix uvflag read/write for better py2/py3 synergy

### ISSUE THREAD

**Issue by adampbeardsley** [HERA-Team/hera_qm#234]
Right now writing a uvflag object with py2, and reading it with py3 results in some unhappy errors.

According to plaplant:
> the safest thing to do when writing them is to explicitly cast to numpy strings: `f['some_attribute'] = np.string_("my string")`. then you unpack them with something like: `mystring = _bytes_to_str(f['some_attribute'].value.tostring())`
I was writing this up as part of my uvh5 memo, if you wanted a worked example.

Also see:
https://github.com/RadioAstronomySoftwareGroup/pyuvdata/blob/master/pyuvdata/uvh5.py#L25

**Comment by plaplant** [comment]
Related to this, special handling needs to happen for the `polarization_array` attribute, which can potentially be a string if multiple polarizations have been combined (either through an `or` operation or an average).

**Comment by adampbeardsley** [comment]
Closed in #271
