### ISSUE TITLE
Update firstcal_metrics for IDR2.2

### ISSUE THREAD

**Issue by jsdillon** [HERA-Team/hera_qm#252]
Right now firstcal metrics doesn't support dual-pol calfits files, which is what redcal will produce. See:
https://github.com/HERA-Team/hera_qm/blob/f7b13d9b2404cc4684ff36ee70fad2aa675b3a36/hera_qm/firstcal_metrics.py#L353

**Comment by adampbeardsley** [comment]
This is a duplicate of #219
