### ISSUE TITLE
Firstcal metrics needs a clobber option

### ISSUE THREAD

**Issue by jsdillon** [HERA-Team/hera_qm#263]
https://github.com/HERA-Team/hera_qm/blob/4485407ef8ce78d0adf60fec5474687c8427683b/hera_qm/firstcal_metrics.py#L830

**Comment by jsdillon** [comment]
Not having clobber makes re-running the pipeline very annoying as we try to debug it.

**Comment by jsdillon** [comment]
Also, xrfi_run needs one.

**Comment by adampbeardsley** [comment]
addressed in #265
