### ISSUE TITLE
Implement absolute chi^2 cut

### ISSUE THREAD

**Issue by adampbeardsley** [HERA-Team/hera_qm#282]
In IDR2.2 we saw a day that had really high chi^2 which wasn't caught by xrfi (didn't really look like RFI). Now that chi^2 is properly normalized, we should have a step in the pipeline to do a straight cut.

**Comment by jsdillon** [comment]
I've documented the issue over at https://github.com/HERA-Team/hera_cal/issues/484

**Comment by adampbeardsley** [comment]
Closed by #287.
