### ISSUE TITLE
Should there be an absolute value here?

### ISSUE THREAD

**Issue by jsdillon** [HERA-Team/hera_qm#286]
Should https://github.com/HERA-Team/hera_qm/blob/393ee1add2bd582b1142f5f5a85ef33664383382/hera_qm/xrfi.py#L697

be `uvf_f.flag_array[np.abs(uvf_m.metric_array) >= nsig_p] = True`?

And likewise, shouldn't there also be absolute values in https://github.com/HERA-Team/hera_qm/blob/393ee1add2bd582b1142f5f5a85ef33664383382/hera_qm/xrfi.py#L595 and 

https://github.com/HERA-Team/hera_qm/blob/393ee1add2bd582b1142f5f5a85ef33664383382/hera_qm/xrfi.py#L606

**Comment by jsdillon** [comment]
Specifically, if a metric is large and negative, that seems like it as much of an outlier as one that's large and positive...

**Comment by adampbeardsley** [comment]
I think you're right. But I'd also like to see how this looks run on actual data before we change it as a "bug fix." What if I include it in the save_more_xrfi_info branch I'm working on right now and we can do the comparison there?

**Comment by jsdillon** [comment]
Fine with me.
