### ISSUE TITLE
Understand/fix file boundaries in xrfi

### ISSUE THREAD

**Issue by adampbeardsley** [HERA-Team/hera_qm#301]
We've noticed relatively strong file boundary issues in the metric calculations in xrfi. We've seen hints in most data products, but is especially strong and consistent in the omnical visibility solutions. Interestingly I can't seem to see it at all in the omnical gains or omnical chisq metrics.

Example from 2458098:
![image](https://user-images.githubusercontent.com/4752917/62319307-8bf64000-b452-11e9-8477-12f12debab5a.png)
(renormalized chi-sq as reference because file boundaries are clear there)

It's not clear why this should be so strong because the median filter reflects at the boundaries, so it should have a reasonable MAD.

@jsdillon I know you started to look into this - any luck?

**Comment by jsdillon** [comment]
The file boundaries in the chi_sq_renormed make sense: if the mean/median chi_sq in a file is bigger (or the variance/MAD) than it is in the next one, the renormalization with create a discontinuity. 

The ones in the omnical visibility solutions are really weird. I don't understand that at all... 

I haven't dug into this any more than just to observe some of what you're seeing there.

**Comment by jsdillon** [comment]
With the new OPM chunking and overlap functionality in XRFI, I think we can close this.
