### ISSUE TITLE
Failure in XRFI step running the IDR2 analysis pipeline

### ISSUE THREAD

**Issue by zacharymartinot** [HERA-Team/hera_qm#309]
I encountered this error while running the IDR2 analysis pipeline in the XRFI step with `pyuvdata: fce2f76c0905e8cf7d954ac569a9df1fa0c52478` (most recent on master)  and  `hera_qm: 597ec3b498ce1b30cbef2736df1addfc4a6b9ffe`

```
xrfi_run.py --ocalfits_file=zen.2458098.13298.HH.omni.calfits --acalfits_file=zen.2458098.1329
8.HH.abs.calfits --model_file=zen.2458098.13298.HH.omni_vis.uvh5 --data_file=zen.2458098.13298
.HH.uvh5 --kt_size=8 --kf_size=8 --sig_init=5.0 --sig_adj=2.0 --clobber
invalid value encountered in subtract
invalid value encountered in greater
invalid value encountered in true_divide
invalid value encountered in greater
invalid value encountered in greater_equal
invalid value encountered in greater_equal
invalid value encountered in greater_equal
All-NaN slice encountered
Traceback (most recent call last):
  File "/lustre/aoc/projects/hera/zmartino/anaconda3/envs/main/bin/xrfi_run.py", line 18, in <
module>
	metrics_file=args.metrics_file, clobber=args.clobber)
  File "/lustre/aoc/projects/hera/zmartino/anaconda3/envs/main/lib/python3.7/site-packages/her
a_qm/xrfi.py", line 1537, in xrfi_run
	run_check_acceptability=run_check_acceptability)
  File "/lustre/aoc/projects/hera/zmartino/anaconda3/envs/main/lib/python3.7/site-packages/her
a_qm/xrfi.py", line 1042, in flag_apply
	run_check_acceptability=run_check_acceptability)
  File "/lustre/aoc/projects/hera/zmartino/anaconda3/envs/main/lib/python3.7/site-packages/pyu
vdata/uvflag.py", line 1936, in to_antenna
	run_check_acceptability=run_check_acceptability)
  File "/lustre/aoc/projects/hera/zmartino/anaconda3/envs/main/lib/python3.7/site-packages/pyu
vdata/uvbase.py", line 277, in check
	eshape=eshape))
ValueError: UVParameter _flag_array is not expected shape. Parameter shape is (52, 1, 1024, 60
, 2), expected shape is (52, 1, 1024, 60, 1).
```

Rolling back to `pyuvdata 1.4.1` release and `hera_qm: 92674044d39a7649d7cb598a922ca4d494c7f768` fixed the issue.

**Comment by adampbeardsley** [comment]
I think I see the problem here. In the `to_antenna` function, the flag array (and other things like polarization array and weights array, metric_array if metric type) get resized if `force_pol` is set, but `Npol` is not reset. Seems like an easy fix, but I'm confused why this wasn't throwing an error in IDR2.2.

side note, it looks like `Npol` does get resent in `to_baseline` when `force_pol` is set. So that's good.

**Comment by mkolopanis** [comment]
This was not an issue in IDR2.2 because the UVFlag upgrades were pretty recent. Most likely it was not even a UVBase'ed object then.

**Comment by mkolopanis** [comment]
Please try the branch from [this PR](https://github.com/RadioAstronomySoftwareGroup/pyuvdata/pull/714) and let me know if it fixes the issue.

**Comment by lwhitler** [comment]
Using the branch @mkolopanis directed to worked for me
