### ISSUE TITLE
End python 2.7 Support

### ISSUE THREAD

**Issue by mkolopanis** [HERA-Team/hera_qm#313]
python 2.7 end of life is 1 Jan 2020. We should prepare for this by ending active support.

**Comment by adampbeardsley** [comment]
Do we actively support? Or does this just mean turning off the CI testing?

**Comment by mkolopanis** [comment]
I would argue turning off tests, and bending over backwards to support it with `six` stuff and all the "trying to make bytes vs unicode" junk go away. I'm sure @plaplant  has many thoughts on the matter

**Comment by mkolopanis** [comment]
Should we tag a version for final python 2 compatible version?

**Comment by plaplant** [comment]
Yeah, we did something similar on `hera_cal`: https://github.com/HERA-Team/hera_cal/tree/last-py2-compatible. I guess it's a branch instead of a tag, I have a slight preference for it being a tag.

**Comment by mkolopanis** [comment]
I do as well.

**Comment by mkolopanis** [comment]
this was done with #314
