### ISSUE TITLE
--skip_red_corr doesn't behave as expected

### ISSUE THREAD

**Issue by jsdillon** [HERA-Team/hera_qm#317]
In ant_metrics, I expect the option --skip_red_corr to not run red_corr metrics for either detecting dead antennas or crossed antennas. This only skips the one for dead antennas, but `redCorrXPol` is still in ant_metrics.

**Comment by jsdillon** [comment]
This is particularly important here:

https://github.com/HERA-Team/hera_qm/blob/1b6a5a0a9f08d22290204e09140944b1e466d35e/hera_qm/ant_metrics.py#L908

If we don't trust the redcorr metrics, we shouldn't be averaging them with the mean Vij-based metrics.

**Comment by adampbeardsley** [comment]
Good catch. Should be an easy fix... I'll give it a go.

**Comment by jsdillon** [comment]
Thanks. I'd he happy to review a PR.
