### ISSUE TITLE
Enable XRFI to take a priori frequency flags

### ISSUE THREAD

**Issue by jsdillon** [HERA-Team/hera_qm#332]
After some discussion in the most recent analysis telecon, it was suggested that we should provide a simple interface (perhaps a text file) specifying ranges in frequency to always flag. 

These should be integrated into XRFI in a self-consistent way, including treating them as high nsigma points so that the watershed algorithm can grow flags around them.

**Comment by bhazelton** [comment]
I suggest the yaml format as very easy to read/edit for people and also easy to parse in python.

**Comment by jsdillon** [comment]
This was done in #359
