### ISSUE TITLE
Speed up tests

### ISSUE THREAD

**Issue by adampbeardsley** [HERA-Team/hera_qm#40]
Working on the latest PR, I noticed the tests take quite a while to complete. Not a huge deal, but we should evaluate to see if there are places we can make more efficient.

**Comment by plaplant** [comment]
When I was working on PR #42, I noticed almost all of the time was spent in tests involving `detrent_medfilt`. I think it's because median filtering is just a very expensive operation. Perhaps we could speed things up by testing on smaller arrays? Not sure there's another easy option.

**Comment by jkerrigan** [comment]
Switching from medfilt to medfilt2d appears to give an 8x speedup. I've tested both on datasets and they appear to give identical output.

**Comment by adampbeardsley** [comment]
Nice work on that Josh. Paul - this may affect what RFI strategy we want in the RTP. But perhaps we shouldn't mess with things right now.

**Comment by adampbeardsley** [comment]
Still a little slow, but not prohibitive.
