### ISSUE TITLE
Modularize auto_view

### ISSUE THREAD

**Issue by adampbeardsley** [HERA-Team/hera_qm#70]
auto_view.py is a script to quickly look at autos to determine the general health of the array. The code needs to be moved into modules and covered with tests.

**Comment by adampbeardsley** [comment]
Unify plots to have similar style, same rows/columns

**Comment by mkolopanis** [comment]
I think this is worth closing, we have #161 tracking auto_view progress. But more importantly it is handled in https://github.com/HERA-Team/simple-dashboard now too.
