### ISSUE TITLE
update firstcal metrics to use json files

### ISSUE THREAD

**Issue by adampbeardsley** [HERA-Team/hera_qm#72]
Will need zero intercept (phase offset) from firstcal

**Comment by dannyjacobs** [comment]
delays are now stored in json files instead of the firscal.calfits 
firstcal metrics needs to be updated to read the json files instead of the calfits files

**Comment by adampbeardsley** [comment]
With PR #81, we went to jsons, then back to calfits. firstcal_metrics now reads in the (gain-type) calfits, and calculates delay and offset, then IDs rotated antennas.
