### ISSUE TITLE
make auto plot a little more 350 friendly

### ISSUE THREAD

**Issue by dannyjacobs** [HERA-Team/hera_qm#93]
set wspace and hspace=0 
Maybe increase number of rows so each plot isn't so narrow.

![2458031 431020 auto_specs](https://user-images.githubusercontent.com/63191/31204894-ed2aed54-a922-11e7-81c2-555f68aea7c1.png)

**Comment by adampbeardsley** [comment]
I think this is done. The position plot will probably need tweaking, but hard to test when we have a subarray.
